"""Generate `data/slots.js` from `data/raw/slots.json`.

The build sheet has 185 item slots across 16 sections. Transcribing that by hand would be
error-prone, so it is generated -- but the output is a plain, readable JS file that can be
hand-edited afterwards if the layout ever needs to diverge from the sheet.

Slot ids are `<section>.<slot>` (e.g. `gear.head`, `companions.utility`). The section prefix is
always present, never conditional on collisions, so an id can never change meaning when a new
slot is added -- saved builds keep working.

Usage:
    ./venv/Scripts/python.exe tools/gen_slots.py
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from nwtools import repo_path      # noqa: E402
from nwtools import jsemit         # noqa: E402

# Slot rows that are *not* item slots in the new model: they set build context instead
# (plan §2.1). Kept here so the generator fails loudly if the sheet grows another one.
#
# The whole Options section qualifies. In the sheet these are pseudo-items -- `Class: Warlock`,
# `Role: DPS`, `Forte: power_p` are rows in db-items with no stats, existing only so the
# string-matching bonus engine can see them. Here they are plain context fields.
CONTEXT_ROWS = {
    14: 'class',        15: 'forte.primary', 16: 'forte.secondaryA', 17: 'forte.secondaryB',
    18: 'role',         19: 'damageType',    20: 'magnitude',        22: 'combatType',
    23: 'duration',     24: 'location',      25: 'toggles.consumables',
    26: 'toggles.party', 27: 'toggles.combat', 28: 'toggles.procs',
    29: 'toggles.artifactCall',              30: 'm32Forte',
}


def slug(text):
    """'Insignia 1.1' -> 'insignia1_1', 'Guild - Offense' -> 'guildOffense'."""
    text = text.strip().replace('.', '_')
    parts = re.split(r'[^A-Za-z0-9_]+', text)
    parts = [p for p in parts if p]
    if not parts:
        return 'slot'
    out = parts[0][0].lower() + parts[0][1:]
    for part in parts[1:]:
        out += part[0].upper() + part[1:]
    # collapse 'Insignia1_1' style: keep underscores, drop stray capitalisation of digits
    return out


def build_slots(raw):
    sections, slots = [], []
    current = None
    skipped = []

    for entry in raw['slots']:
        row, label, kind = entry['row'], entry['label'], entry['kind']

        if kind == 'section':
            current = {'id': slug(label), 'label': label, 'row': row}
            sections.append(current)
            continue

        if row in CONTEXT_ROWS:
            continue

        if kind != 'item':
            skipped.append((row, label, kind))
            continue

        if current is None:
            raise SystemExit(f'slot {label!r} at row {row} precedes any section header')

        filt = entry.get('filter')
        if not filt:
            raise SystemExit(
                f'slot {label!r} at row {row} has no resolvable filter '
                f'({entry.get("unresolvedRange")!r}) -- fix sync_sheet.py before generating'
            )

        slots.append({
            'id': current['id'] + '.' + slug(label),
            'label': label,
            'section': current['id'],
            'filter': filt,
            'row': row,
        })

    return sections, slots, skipped


def main():
    raw_path = repo_path('data', 'raw', 'slots.json')
    if not os.path.exists(raw_path):
        raise SystemExit(f'missing {raw_path} -- run tools/sync_sheet.py first')

    raw = json.load(open(raw_path, encoding='utf-8'))
    sections, slots, skipped = build_slots(raw)

    unexpected = [s for s in skipped if s[0] not in CONTEXT_ROWS]
    if unexpected:
        raise SystemExit(
            'unclassified non-item rows (add them to CONTEXT_ROWS or fix the sheet): '
            + repr(unexpected)
        )

    ids = [s['id'] for s in slots]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        raise SystemExit(f'duplicate slot ids: {dupes}')

    # The Options section is entirely context now, so it holds no slots. Drop empties rather
    # than emit a section the UI would render as a blank panel.
    used = {s['section'] for s in slots}
    sections = [s for s in sections if s['id'] in used]

    out = repo_path('data', 'slots.js')
    lines = [
        '// GENERATED by tools/gen_slots.py from data/raw/slots.json -- do not edit by hand',
        '// unless you intend the app layout to diverge from the source spreadsheet.',
        '//',
        '// Slot ids are `<section>.<slot>` and are stable: the section prefix is unconditional,',
        '// so adding a slot can never change an existing id and break saved builds.',
        '//',
        '// The sheet\'s whole Options section is deliberately absent: Class, Role, the three',
        '// Forte picks, Damage Type, Magnitude, Combat Type, Duration, Location, the five effect',
        '// toggles and M32 Forte are build *context* now, not item slots. In the sheet they were',
        '// pseudo-items with no stats, existing only so the string-matching bonus engine could',
        '// count them. See data/schema.js `context` and plan §2.1.',
        '',
        'window.NW_SLOTS = {',
        '  sections: ' + jsemit.value(sections, 2, width=96) + ',',
        '  slots: [',
    ]
    body = ['    ' + jsemit.value(slot, 4, width=1000) for slot in slots]
    lines.append(',\n'.join(body))
    lines += ['  ]', '};', '']

    with open(out, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(lines))

    print(f'wrote {out}')
    print(f'  {len(sections)} sections, {len(slots)} slots')
    by_filter = {}
    for slot in slots:
        by_filter[slot['filter']] = by_filter.get(slot['filter'], 0) + 1
    print(f'  {len(by_filter)} distinct filters')


if __name__ == '__main__':
    main()
