// Statically-imported game data, replacing the classic fetch+window-global loaders
// (data/*.js, deleted this phase) that used to populate window.NW_SCHEMA/NW_SLOTS/NW_ITEMS/
// NW_BONUSES. `data/schema.json` is hand-written/authoritative; `data/slots.json`,
// `data/db-items.json` and `data/db-bonuses.json` are GENERATED via tools/*.py -- never hand-
// edit those three, regenerate them instead. Not-yet-converted classic files (App.vue, most of
// src/components/) still read NW_SCHEMA etc as globals -- src/legacy-bridge.ts bridges these
// exports back onto window for their sake until they convert too (Phase 5/6).
//
// `deriveSchema` ports data/schema.js's derivation logic verbatim (byKey/statKeys/etc). That
// file's header comment carried the FIX-note provenance for schema.json's fields, reproduced
// here since the loader file itself is gone:
//
// The raw values (stat list, caps, ability contributions, roles, context) are HAND-WRITTEN AND
// AUTHORITATIVE in schema.json. Reverse-engineered from `test-dev` rows 236-253; see
// llm/plans/0001-web-builder-implementation.md §1.3 for the derivation and §3 for the
// deviations from the sheet, each one marked `FIX #n` below against the field it touches. JSON
// has no comment syntax, so that provenance lives here, next to the code that reads the field,
// rather than in the data file itself.
//
// FIX #3 (schema.json `stats`): `control_resist` / `control_resist_p` exist in the build sheet
//   but had no db-items columns, so no item could ever grant them. They are first-class stats.
// FIX #4 (schema.json `stats`): the sheet's `dmg_enchant` column is absent -- it mapped to no
//   db-items column and always resolved to 0.
// FIX #5 (schema.json `abilityContributions`): `mult_hit_points` was merged with an algebraic
//   hack in the sheet because the row was additive; here con/200 is simply another `mult`
//   factor.
//
// Stat `kind`:
//   flat     plain additive number (item level, hit points, ability scores)
//   rating   additive; receives `combined_rating`; capped at IL + allowedOver
//   percent  additive fraction (0.09 === 9%); may be capped
//   mult     combines multiplicatively across sources: prod(1 + v) - 1
// `enemy` marks the opposing-side stats, which share the pipeline but are displayed apart. The
// labels carry the word "Enemy" because they are shown far from the enemy table -- in item
// cards, bonus payloads and item previews -- where `Accuracy` is indistinguishable from the
// player's `acc_p`. The stat panel's enemy table strips the prefix back off, since its own
// heading already says it.
//
// Rating -> percent conversion (pipeline rows 241-243, caps row 251):
//   pct += capPct - max(IL + allowedOver - ratingTotal, 0) / 100000
//   ratingCap = IL + allowedOver
//
// Ability contributions: `divisor` is the sheet's literal divisor (pipeline row 245).
//
// Forte redistribution (pipeline rows 247-249): the chosen primary forte stat receives
// forte_p/2; each secondary receives forte_p/4 -- see `forteSplit`.
//
// `context` replaces the sheet's pseudo-item option rows entirely (plan §2.1). Duration is a
// free number of seconds; `context.durationPresets` are UI convenience only, not a bucket.
//
// The slot list is *not* here -- it is generated into data/slots.json from data/raw/slots.json
// (via tools/gen_slots.py), because 185 slots is too many to transcribe reliably by hand. Slot
// ids are `<section>.<slot>` and stable: the section prefix is unconditional, so adding a slot
// can never change an existing id and break saved builds. `data/db-items.json` is generated by
// tools/migrate_bonuses.py from data/raw/db-items.json; `data/db-bonuses.json` by the same
// script -- every bonus, one per set, membership living on the items (`bonuses: [...]`), never
// on the set itself (see CLAUDE.md's "Items reference a bonus set by id, never by name").

import rawSchema from '../data/schema.json';
import rawSlots from '../data/slots.json';
import rawItems from '../data/db-items.json';
import rawBonusSets from '../data/db-bonuses.json';
import type { Schema, StatDef, StatKey, SlotsData, Item, BonusSet } from './types';

function deriveSchema(raw: typeof rawSchema): Schema {
  const byKey = {} as Record<StatKey, StatDef>;
  raw.stats.forEach((s) => { byKey[s.key] = s; });

  return {
    stats: raw.stats,
    statByKey: byKey,
    statKeys: raw.stats.map((s) => s.key),
    multiplicativeStats: raw.stats.filter((s) => s.kind === 'mult').map((s) => s.key),
    ratingStats: raw.stats.filter((s) => s.kind === 'rating').map((s) => s.key),
    abilityStats: raw.stats.filter((s): boolean => 'ability' in s && Boolean(s.ability)).map((s) => s.key),
    ratingConversion: raw.ratingConversion,
    abilityContributions: raw.abilityContributions,
    forteSplit: raw.forteSplit,
    roles: raw.roles,
    context: raw.context,
  };
}

export const NW_SCHEMA: Schema = deriveSchema(rawSchema);
export const NW_SLOTS: SlotsData = rawSlots;
export const NW_ITEMS: Item[] = rawItems;
export const NW_BONUSES: BonusSet[] = rawBonusSets;
